%%  base matrices B0 (p x p) and A0 (5 x 5) are generated by the designated server.
%   - Apply d-transformation to intercept column
%   - Generate orthogonal matrix M_i
%   - Generate random coefficient vectors b_i, a_i
%   - Compute B_i and A_i as matrix polynomials

    %% Load parameters and raw data
    load('global_params.mat', 'p', 'd', 'n');
    load(sprintf('raw_data_agency_%d.mat', i), 'X', 'Y');

    %% d-transformation: multiply first column (intercept) by d
    X(:, 1) = d * X(:, 1);
    fprintf('Agency %d: d-transformation applied (d = %g)\n', i, d);

    %% Generate n x n orthogonal matrix M_i via QR decomposition
    rng(i * 100);   % seed for reproducibility
    [M, ~] = qr(randn(n, n));
    fprintf('Agency %d: Orthogonal matrix M (%dx%d) generated\n', i, n, n);

    %% Generate random coefficient vectors
    rng(i * 200);
    b = randn(p, 1);    % p-dimensional for B_i
    a = randn(5, 1);    % 5-dimensional for A_i
 
    %% Compute B_i = sum_{j=1}^{p} b_{ij} * B0^j
    B = zeros(p, p);
    B0_power = eye(p);
    for j = 1:p
        B0_power = B0_power * B0;
        B = B + b(j) * B0_power;
    end
    fprintf('Agency %d: Matrix B (%dx%d) computed\n', i, p, p);

    %% Compute A_i = sum_{j=1}^{5} a_{ij} * A0^j
    A = zeros(5, 5);
    A0_power = eye(5);

    for j = 1:5
        A0_power = A0_power * A0;
        A = A + a(j) * A0_power;
    end
    fprintf('Agency %d: Matrix A (5x5) computed\n', i);



%   - Generate pseudo outcomes Y_s1, Y_s2, Y_s3, Y_s4
%   - Form augmented outcome matrix Y_iA
%   - Apply internal encryption: X* = M_i * X_i * B_i
%                                 Y* = M_i * Y_iA * A_i

    %% Load parameters
    load('global_params.mat', 'alpha');
    
    n = size(X, 1);

    %% Generate pseudo outcomes
    % Y_s1i: sum of all columns of X_i
    Y_s1 = sum(X, 2);                          % n x 1
    fprintf('Agency %d: Y_s1 generated (sum of X columns)\n', i);

    % Y_s2i: vector of zeros
    Y_s2 = zeros(n, 1);                         % n x 1
    fprintf('Agency %d: Y_s2 generated (zeros)\n', i);

    % Y_s3i: Y_i + Y_s1i + Y_s2i
    Y_s3 = Y + Y_s1 + Y_s2;                    % n x 1
    fprintf('Agency %d: Y_s3 generated (Y + Y_s1 + Y_s2)\n', i);

    % Y_s4i: alpha * ones
    Y_s4 = alpha * ones(n, 1);                  % n x 1
    fprintf('Agency %d: Y_s4 generated (alpha * ones, alpha = %g)\n', i, alpha);

    %% Form augmented outcome matrix Y_iA (n x 5)
    Y_iA = [Y, Y_s1, Y_s2, Y_s3, Y_s4];
    fprintf('Agency %d: Y_iA formed (%dx5)\n', i, n);

    %% Internal encryption
    X_star = M * X  * B;       % n x p
    Y_star = M * Y_iA * A;     % n x 5
    fprintf('Agency %d: Internal encryption done\n', i);
    fprintf('  X_star size: [%d x %d]\n', size(X_star,1), size(X_star,2));
    fprintf('  Y_star size: [%d x %d]\n', size(Y_star,1), size(Y_star,2));
